config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  get '/recommendations', to: 'recommendations#index'
  get '/identifications', to: 'identifications#index'

  resources :users do
    member do
      get '/recommendation',    to: 'recommendations#show'
      get '/edit_recommendation', to: 'recommendations#edit', as: :edit_recommendation
      get '/new_recommendation', to: 'recommendations#new', as: :new_recommendation
      post '/recommendation',   to: 'recommendations#create'
      patch '/recommendation',  to: 'recommendations#update'
      delete '/recommendation', to: 'recommendations#destroy'

      get '/identification',    to: 'identifications#show'
      get '/edit_identification', to: 'identifications#edit', as: :edit_identification
      get '/new_identification', to: 'identifications#new', as: :new_identification
      post '/identification',   to: 'identifications#create'
      patch '/identification',  to: 'identifications#update'
      delete '/identification', to: 'identifications#destroy'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recommendations, dependent: :destroy
  has_many :identifications, dependent: :destroy
  accepts_nested_attributes_for :recommendations, allow_destroy: true
  accepts_nested_attributes_for :identifications, allow_destroy: true

  validates :name, presence: true, length: { maximum: 120 }
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :dob, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
    respond_to :html, :json
  end

  def show
    @recommendation = @user.recommendations.last
    @recommendation_image = recommendation_image ? recommendation_image : nil
    @identification = @user.identifications.last
    @identification_image = identification_image ? identification_image : nil
    respond_to :html, :json
  end

  def new
    @user = User.new
    # @identification = Identification.new
  end

  def edit
    @identification = @user.identifications.last
  end

  def create
    user = user_params.except(:recommendation_attributes, :identification_attributes)
    @user = User.new(user)
    if @user.save
      if user_params.dig(:recommendation_attributes)
        @user.recommendations.create(user_params[:recommendation_attributes])
      end
      if user_params.dig(:identification_attributes)
        @user.identifications.create(user_params[:identification_attributes])
      end
      respond_to do |format|
        format.html { redirect_to user_path(@user), notice: 'User was successfully created.' }
        format.json { render 'create', status: :created }
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
        user = user_params.except(:recommendation_attributes, :identification_attributes)

    if @user.update(user)
      if user_params.dig(:recommendation_attributes)
        @user.recommendations.create(user_params[:recommendation_attributes])
      end
      if user_params.dig(:identification_attributes)
        @user.identifications.create(user_params[:identification_attributes])
      end

      respond_to do |format|
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { render json: :nothing, status: 204 }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :name, :email, :dob,
      recommendation_attributes: [
        :number, :issuer, :state, :expiration, :id, :image_upload
      ],
      identification_attributes: [
        :number, :state, :expiration, :id, :image_upload
      ])
  end

  def recommendation_image
    @user.recommendations.try(:last).try(:image_upload)
  end

  def identification_image
    @user.identifications.try(:last).try(:image_upload)
  end
end

app/views/users/show/_identification.html.erb
<% if @identification %>
<div class="image_upload">
  <% if @identification_image.attached? %>
    <%= image_tag @identification_image, width: 200 %>
  <% else %>
    <%= link_to 'add identifcation image', edit_identification_user_path %>
  <% end %>
</div>

<p>
  <strong>Number:</strong>
  <%= @identification.number %>
</p>

<p>
  <strong>State:</strong>
  <%= @identification.state %>
</p>

<p>
  <strong>Expiration:</strong>
  <%= @identification.expiration %>
</p>
  <%= link_to "Edit", edit_identification_user_path %>
<% else %>
  <%= link_to "Add State info", new_identification_user_path, class: 'button' %>
<% end %>

app/views/users/show/_recommendation.html.erb
<% if @recommendation %>
<div class="image_upload">
  <% if @recommendation_image.attached? %>
    <%= image_tag @recommendation_image, width: 200 %>
  <% else %>
    <%= link_to 'add recommendation image', edit_recommendation_user_path %>
  <% end %>
</div>

<p>
  <strong>Number:</strong>
  <%= @recommendation.number %>
</p>

<p>
  <strong>Issuer:</strong>
  <%= @recommendation.issuer %>
</p>

<p>
  <strong>State:</strong>
  <%= @recommendation.state %>
</p>

<p>
  <strong>Expiration:</strong>
  <%= @recommendation.expiration %>
</p>
<%= link_to "Edit", edit_recommendation_user_path %>
<% else %>
  <%= link_to "Add Recommendation", new_recommendation_user_path, class: 'button' %>
<% end %>