config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  get '/recommendations', to: 'recommendations#index'
  get '/identifications', to: 'identifications#index'

  resources :users do
    member do
      get '/recommendation',    to: 'recommendations#show'
      get '/edit_recommendation', to: 'recommendations#edit', as: :edit_recommendation
      get '/new_recommendation', to: 'recommendations#new', as: :new_recommendation
      post '/recommendation',   to: 'recommendations#create'
      patch '/recommendation',  to: 'recommendations#update'
      delete '/recommendation', to: 'recommendations#destroy'

      get '/identification',    to: 'identifications#show'
      get '/edit_identification', to: 'identifications#edit', as: :edit_identification
      get '/new_identification', to: 'identifications#new', as: :new_identification
      post '/identification',   to: 'identifications#create'
      patch '/identification',  to: 'identifications#update'
      delete '/identification', to: 'identifications#destroy'
    end
  end
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  belongs_to :user
  validates :number, presence: true, length: { maximum: 120 }
  validates :issuer, presence: true, length: { maximum: 120 }
  validates :state, presence: true, length: { maximum: 2 }
  has_one_attached :image_upload

  def is_expired?
    self.expiration < 1.day.ago
  end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  before_action :set_recommendation, only: [:show, :edit, :update, :destroy]

  def index
    @recommendations = Recommendation.all
    respond_to do |format|
      format.html
      format.json { render json: @recommendations, status: :ok }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @recommendation, status: :ok }
    end
  end

  def new
    @user = User.find(params[:id])
    @recommendation = Recommendation.new(user: @user)
  end

  def edit
  end

  def create
    @recommendation = Recommendation.new(user_recommendation_params)
    if @recommendation.save
      respond_to do |format|
        format.html { redirect_to user_path(@recommendation.user_id), notice: 'Recommendation was successfully created.' }
        format.json { render json: @recommendation, status: :created }
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @recommendation.update(recommendation_params)
      respond_to do |format|
        format.html { redirect_to user_path(@recommendation.user_id), notice: 'Recommendation was successfully updated.' }
        format.json { render json: @recommendation, status: :ok }
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recommendation.destroy
    respond_to do |format|
      format.html { redirect_to user_path(@recommendation.user_id), notice: 'Recommendation was successfully destroyed.' }
      format.json { render json: :nothing, status: 204 }
    end
  end

  private
    def set_recommendation
      set_user
      @recommendation = @user.recommendations.last
    end

    def set_user
      user = if params.dig(:recommendation, :user_id)
        params[:recommendation][:user_id]
      else
        params[:id]
      end
      @user = User.find(user)
    end

    def recommendation_params
      params.require(:recommendation).permit(:user_id, :number, :issuer, :state, :expiration, :image_upload, { user_id: [ :id ] })
    end

    def user_recommendation_params
      user_id = params[:id] ? params[:id] : params[:user_id]
      recommendation_params.merge({user_id: user_id})
    end
end

app/views/recommendations/_form.html.erb
<%= form_with(model: [@user, @recommendation], url: recommendation_user_path, local: true) do |form| %>
<%= render 'shared/errors', model: recommendation %>

<div class="field columns">
  <div class="control column is-4">
    <%= form.label :number, class: 'label' %>
    <%= form.text_field :number, class: 'control input' %>
  </div>

  <div class="control column is-4">

    <%= form.label :issuer, class: 'label' %>
    <%= form.text_field :issuer, class: 'control input' %>
  </div>

  <div class="field column is-2">
    <%= form.label :state, class: 'label' %>
    <%= form.text_field :state,class: 'control input' %>
  </div>
</div>

<div class="field columns">
  <div class="field column">
    <%= form.label :expiration, class: 'label' %>
    <%= form.date_select :expiration,class: 'control input' %>
  </div>
  <div class="field column">
    <%= form.label 'proof', class: 'label' %>
    <%= form.file_field :image_upload %>
  </div>
</div>

<div class="field">
  <% if action_name == 'edit' %>
  <%= link_to 'Cancel', user_path(@recommendation.user_id), class: 'button is-warning' %>
  <%= link_to 'Delete', recommendation_user_path(@user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-danger' %>
  <%= form.submit 'Save', class:'button is-primary' %>
  <% else %>
  <%= link_to 'Cancel', user_path(@recommendation.user_id), class: 'button is-warning' %>
  <%= form.submit 'Save', class:'button is-primary' %>
  <% end %>
</div>
<% end %>

app/views/recommendations/_show.html.erb
<% if @recommendation %>
<h1 class="title">Medical Recommendation</h1>
<div class="image_upload">
  <% if @recommendation_image.attached? %>
    <%= image_tag @recommendation_image, width: 200 %>
  <% else %>
    <%= link_to 'add recommendation image', edit_recommendation_user_path %>
  <% end %>
</div>

<p>
  <strong>Number:</strong>
  <%= @recommendation.number %>
</p>

<p>
  <strong>Issuer:</strong>
  <%= @recommendation.issuer %>
</p>

<p>
  <strong>State:</strong>
  <%= @recommendation.state %>
</p>

<p>
  <strong>Expiration:</strong>
  <%= @recommendation.expiration %>
</p>
<div class="has-text-right">
  <%= link_to "Edit", edit_recommendation_user_path, class: 'button' %>
</div>
<% else %>
<div class="has-text-right">
  <%= link_to "Add Recommendation", new_recommendation_user_path, class: 'button' %>
</div>
<% end %>

app/views/recommendations/edit.html.erb
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h2 class='subtitle is-4 has-text-grey'>Edit Recommendation</h2>
      <%= render 'form', recommendation: @recommendation %>
    </div>
  </div>
</section>

app/views/recommendations/new.html.erb
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h2 class='subtitle is-4 has-text-grey'>New Recommendation</h2>
      <%= render 'form', user: @user, recommendation: @recommendation %>
    </div>
  </div>
</section>