config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  get '/recommendations', to: 'recommendations#index'
  get '/identifications', to: 'identifications#index'

  resources :users do
    member do
      get '/recommendation',    to: 'recommendations#show'
      get '/edit_recommendation', to: 'recommendations#edit', as: :edit_recommendation
      get '/new_recommendation', to: 'recommendations#new', as: :new_recommendation
      post '/recommendation',   to: 'recommendations#create'
      patch '/recommendation',  to: 'recommendations#update'
      delete '/recommendation', to: 'recommendations#destroy'

      get '/identification',    to: 'identifications#show'
      get '/edit_identification', to: 'identifications#edit', as: :edit_identification
      get '/new_identification', to: 'identifications#new', as: :new_identification
      post '/identification',   to: 'identifications#create'
      patch '/identification',  to: 'identifications#update'
      delete '/identification', to: 'identifications#destroy'
    end
  end
end

app/models/identification.rb
class Identification < ApplicationRecord
  belongs_to :user
  validates :number, presence: true, length: { maximum: 120 }
  validates :state, presence: true, length: { maximum: 2 }
  has_one_attached :image_upload

  def is_expired?
    self.expiration < 1.day.ago
  end
end

app/controllers/identifications_controller.rb
class IdentificationsController < ApplicationController
  before_action :set_identification, only: [:show, :edit, :update, :destroy]

  def index
    @identifications = Identification.all
    respond_to do |format|
      format.html
      format.json { render json: @identifications, status: :ok }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @identification, status: :ok }
    end
  end

  def new
    @user = User.find(params[:id])
    @identification = Identification.new(user: @user)
  end

  def edit
  end

  def create
    @identification = Identification.new(user_identification_params)
    if @identification.save
      respond_to do |format|
        format.html { redirect_to user_path(@identification.user_id), notice: 'Identification was successfully created.' }
        format.json { render json: @identification, status: :created }
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @identification.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @identification.update(identification_params)
      respond_to do |format|
        format.html { redirect_to  user_path(@identification.user_id), notice: 'Identification was successfully updated.' }
        format.json { render json: @identification, status: :ok }
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.json { render json: @identification.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @identification.destroy
    respond_to do |format|
      format.html { redirect_to user_path(@identification.user_id), notice: 'Identification was successfully destroyed.' }
      format.json { render json: :nothing, status: 204 }
    end
  end

  private
    def set_identification
      set_user
      @identification = @user.identifications.last
    end

    def set_user
      user = if params.dig(:identification, :user_id)
        params[:identification][:user_id]
      else
        params[:id]
      end
      @user = User.find(user)
    end

    def identification_params
      params.require(:identification).permit(:user_id, :number, :issuer, :state, :expiration, :image_upload, { user_id: [ :id ] })
    end

    def user_identification_params
      user_id = params[:id] ? params[:id] : params[:user_id]
      identification_params.merge({user_id: user_id})
    end
end

app/views/identifications/_form.html.erb
<%= form_with(model: [@user, @identification], url: identification_user_path, local: true) do |form| %>
  <%= render 'shared/errors', model: identification %>

<div class="field columns">
  <div class="control column is-6">
    <%= form.label :number, class: 'label' %>
    <%= form.text_field :number, class: 'control input' %>
  </div>

  <div class="field column is-2">
    <%= form.label :state, class: 'label' %>
    <%= form.text_field :state,class: 'control input' %>
  </div>
</div>

<div class="field columns">
  <div class="field column">
    <%= form.label :expiration, class: 'label' %>
    <%= form.date_select :expiration,class: 'control input' %>
  </div>

  <div class="field column">
    <%= form.file_field :image_upload %>
  </div>

</div>

<div class="field">
  <% if action_name == 'edit' %>
    <%= link_to 'Cancel', user_path(@user), class: 'button is-warning' %>
    <%= link_to 'Delete', identification_user_path, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-danger' %>
    <%= form.submit 'Save', class:'button is-primary' %>
  <% else %>
    <%= link_to 'Cancel', user_path(@user), class: 'button is-warning' %>
    <%= form.submit 'Save', class:'button is-primary' %>
  <% end %>
</div>
<% end %>

app/views/identifications/_show.html.erb
<% if @identification %>
<h1 class="title">State ID</h1>
<div class="image_upload">
  <% if @identification_image.attached? %>
    <%= image_tag @identification_image, width: 200 %>
  <% else %>
    <%= link_to 'add identifcation image', edit_identification_user_path %>
  <% end %>
</div>

<p>
  <strong>Number:</strong>
  <%= @identification.number %>
</p>

<p>
  <strong>State:</strong>
  <%= @identification.state %>
</p>

<p>
  <strong>Expiration:</strong>
  <%= @identification.expiration %>
</p>
<div class="has-text-right">
  <%= link_to "Edit", edit_identification_user_path, class: 'button' %>
</div>
<% else %>
<div class="has-text-right">
  <%= link_to "Add State identification", new_identification_user_path, class: 'button' %>
</div>
<% end %>

app/views/identifications/edit.html.erb
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h2 class='subtitle is-4 has-text-grey'>Edit Identification</h2>
      <%= render 'form', identification: @identification %>
    </div>
  </div>
</section>

app/views/identifications/new.html.erb
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h2 class='subtitle is-4 has-text-grey'>New Identification</h2>
      <%= render 'form', identification: @identification %>
    </div>
  </div>
</section>